kind: Service
apiVersion: v1
metadata:
  name: helloworld-service-canary
spec:
  type: NodePort
  selector:
    app: helloworld-nodejs
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-canary
  labels:
    app: helloworld-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-nodejs
      track: canary
  template:
    metadata:
      labels:
        app: helloworld-nodejs
        track: canary
    spec:
      containers:
      - name: helloworld-nodejs
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
